cmake_minimum_required(VERSION 3.20)

# Explicit union of runtime loaders and all selectable quality tiers:
# src/canonical_inventory.cpp, src/scene_renderer.cpp, src/engine.cpp,
# include/texture_variants.h. Metadata-only moon paths are NOT runtime assets.
set(runtime_textures
  8k_stars.jpg
  stars_milky_way.jpg
  4k_ceres_fictional.jpg
  4k_eris_fictional.jpg
  4k_haumea_fictional.jpg
  4k_makemake_fictional.jpg
  earth_clouds.jpg
  earth_daymap.jpg
  earth_nightmap.jpg
  earth_specular.png
  jupiter.jpg
  mars.jpg
  mercury.jpg
  moon.jpg
  neptune.jpg
  saturn.jpg
  saturn_ring_alpha.png
  sun.jpg
  uranus.jpg
  venus_atmosphere.jpg
  venus_surface.jpg

  # Approved global moon maps only; neutral albedo is generated by OpenGL.
  Derived/enceladus_albedo_2048.jpg
  Derived/enceladus_albedo_4096.jpg
  Derived/europa_jpl_1440.jpg
  Derived/europa_vuu2_jpl_1440.jpg
  Derived/ganymede_jpl_1440.jpg
  Derived/ganymede_vuu2_jpl_1440.jpg

  # Reachable scientific layers, including every Venus Surface quality tier.
  Derived/earth_relief_jpl_1440.jpg
  Derived/mars_viking_jpl_1440.jpg
  Derived/venus_clouds_jpl_1440.jpg
  Derived/venus_radar_ajj2_1440.jpg
  Derived/venus_radar_auu1_720.jpg
  Derived/venus_radar_jpl_1440.jpg

  # Low, Medium, High and Ultra scientific starfields.
  Derived/stars_yale_2880.jpg
  Derived/stars_hipparcos_2880.jpg
  Derived/stars_tycho_2880.jpg
  Derived/stars_scientific_full_2880.jpg
)

if(NOT DEFINED SOURCE_TEXTURE_DIR OR NOT DEFINED DESTINATION_TEXTURE_DIR)
  message(FATAL_ERROR "Texture staging requires source and destination directories")
endif()

# Refuse overlapping paths (including symlink aliases) before destructive cleanup.
# In-source output must never remove repository textures.
file(REAL_PATH "${SOURCE_TEXTURE_DIR}" source_dir)
file(REAL_PATH "${DESTINATION_TEXTURE_DIR}" destination_dir)
cmake_path(IS_PREFIX source_dir "${destination_dir}" NORMALIZE destination_in_source)
cmake_path(IS_PREFIX destination_dir "${source_dir}" NORMALIZE source_in_destination)
if(destination_in_source OR source_in_destination)
  message(FATAL_ERROR "Runtime texture staging must not overlap source textures")
endif()

# Fail before removing the previous staging set if any curated asset is missing.
foreach(texture IN LISTS runtime_textures)
  if(NOT EXISTS "${source_dir}/${texture}" OR IS_DIRECTORY "${source_dir}/${texture}")
    message(FATAL_ERROR "Missing runtime texture: ${source_dir}/${texture}")
  endif()
endforeach()

# Replace, rather than overlay: obsolete files and source-master subtrees from
# earlier broad copies must disappear even when no executable relink is needed.
file(REMOVE_RECURSE "${destination_dir}")
file(MAKE_DIRECTORY "${destination_dir}" "${destination_dir}/Derived")
foreach(texture IN LISTS runtime_textures)
  configure_file("${source_dir}/${texture}" "${destination_dir}/${texture}" COPYONLY)
endforeach()
