cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED SOURCE_ROOT OR NOT DEFINED DESTINATION_ROOT)
  message(FATAL_ERROR "Runtime staging requires source and destination roots")
endif()
file(REAL_PATH "${SOURCE_ROOT}" source_root)
file(REAL_PATH "${DESTINATION_ROOT}" destination_root)
if(source_root STREQUAL destination_root)
  message(FATAL_ERROR "Refusing to stage over the source checkout")
endif()
# Only these dedicated staged directories are replaceable. No source directory
# may lie within them, including symlink aliases.
foreach(directory Textures shaders assets)
  set(destination "${destination_root}/${directory}")
  if(EXISTS "${destination}")
    file(REAL_PATH "${destination}" destination)
  endif()
  cmake_path(IS_PREFIX destination "${source_root}" NORMALIZE overlaps_source)
  file(REAL_PATH "${source_root}/${directory}" source)
  cmake_path(IS_PREFIX source "${destination}" NORMALIZE overlaps_assets)
  if(overlaps_source OR overlaps_assets)
    message(FATAL_ERROR "Runtime staging directory overlaps source: ${destination}")
  endif()
endforeach()
foreach(required assets/fonts/Inter.ttf assets/fonts/OFL.txt assets/audio/out-in-space-menu.ogg assets/audio/out-in-space.ogg icon.png icon.ico LICENSE THIRD_PARTY_NOTICES.md)
  if(NOT EXISTS "${source_root}/${required}")
    message(FATAL_ERROR "Missing runtime asset ${required}")
  endif()
endforeach()
set(SOURCE_TEXTURE_DIR "${source_root}/Textures")
set(DESTINATION_TEXTURE_DIR "${destination_root}/Textures")
include("${source_root}/cmake/StageRuntimeTextures.cmake")
foreach(directory shaders assets)
  file(REMOVE_RECURSE "${destination_root}/${directory}")
endforeach()
file(MAKE_DIRECTORY "${destination_root}/shaders" "${destination_root}/assets/fonts" "${destination_root}/assets/audio" "${destination_root}/assets/branding")
file(GLOB shader_files "${source_root}/shaders/*.vert" "${source_root}/shaders/*.frag" "${source_root}/shaders/*.comp")
foreach(shader IN LISTS shader_files)
  get_filename_component(name "${shader}" NAME)
  configure_file("${shader}" "${destination_root}/shaders/${name}" COPYONLY)
endforeach()
foreach(asset fonts/Inter.ttf fonts/OFL.txt audio/out-in-space-menu.ogg audio/out-in-space.ogg audio/provenance.json branding/mark.png branding/mark.svg branding/logo.png branding/logo.svg)
  configure_file("${source_root}/assets/${asset}" "${destination_root}/assets/${asset}" COPYONLY)
endforeach()
foreach(asset icon.png icon.ico LICENSE THIRD_PARTY_NOTICES.md)
  configure_file("${source_root}/${asset}" "${destination_root}/${asset}" COPYONLY)
endforeach()

file(GLOB license_files "${source_root}/assets/licenses/*.txt")
file(MAKE_DIRECTORY "${destination_root}/assets/licenses")
foreach(license IN LISTS license_files)
  get_filename_component(name "${license}" NAME)
  configure_file("${license}" "${destination_root}/assets/licenses/${name}" COPYONLY)
endforeach()
